### ISSUE TITLE
Linux Mint support

### ISSUE THREAD

**Issue by WildCarrot** [brokengoose/update-o-matic#3]
It should be easy to add support for Linux Mint, since it's based on Ubuntu and uses the `apt` system for updates.

**Comment by brokengoose** [comment]
I don't have a Mint machine for testing. 

You're welcome to create a PR. If you do, please don't just look for the presence of apt, dpkg, etc. Figure out which distribution it is, then use the tools for that distribution. A few distributions include tools that shouldn't be used (e.g. some Debian-based distros sometimes include rpm for LSB compatibility, but you should avoid it.)
